sonar.scm.provider=git

sonar.projectKey=stevethedev_std-website
sonar.organization=stevethedev

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=std-website
#sonar.projectVersion=1.0

# Testing Information
sonar.test.inclusions=clients/src/**/*.spec.ts,server-api/cmd/**/*_test.go,server-api/internal/**/*_test.go
sonar.coverage.exclusions=clients/src/**/*.spec.ts,server-api/cmd/**/*_test.go,server-api/internal/**/*_test.go
sonar.coverage.inclusions=clients/src/**/*.ts,server-api/cmd/**/*.go,server-api/internal/**/*.go

sonar.javascript.lcov.reportPaths=clients/coverage/lcov.info
sonar.typescript.lcov.reportPaths=clients/coverage/lcov.info
sonar.go.coverage.reportPaths=server-api/coverage/coverage.out
