swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: Steve the Dev API Server
host: api.localhost
tags:
  - name: auth
    description: Authentication System
schemes:
  - "https"
  - "http"
paths:
  /auth/check:
    get:
      tags:
        - auth
      summary: Check the authentication token
      description: ""
      produces:
        - application/json
      responses:
        "200":
          description: User is authenticated
          schema:
            $ref: "#/definitions/User"
        "401":
          description: User is not authenticated
          schema:
            type: null

  /auth/login:
    post:
      tags:
        - auth
      summary: Attempt to authenticate with the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Authentication attempt
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: The username to authenticate with.
              password:
                type: string
                description: The password to authenticate with.
      responses:
        "200":
          description: Successful authentication
          schema:
            $ref: "#/definitions/AuthToken"
        "400":
          description: Malformed authentication credentials
        "401":
          description: Authentication failed

  /auth/blacklist:
    post:
      tags:
        - auth
      summary: Blacklist an authentication token so it cannot be used or refreshed
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - api_key: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful authentication
          schema:
            $ref: "#/definitions/AuthToken"
        "400":
          description: Malformed authentication credentials
        "401":
          description: Blacklist permission is denied

  /auth/extend:
    post:
      tags:
        - auth
      summary: Extend the authentication credentials
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Refresh token
          required: true
          schema:
            type: string
            description: The issued refresh token
      security:
        - api_key: []
      responses:
        "200":
          description: Successful refresh
          schema:
            $ref: "#/definitions/AuthToken"
        "400":
          description: Malformed request
        "401":
          description: Refresh failed

securityDefinitions:

  api_key:
    type: apiKey
    name: Authentication
    in: header

definitions:

  User:
    type: object
    properties:
      username:
        type: string
        description: Unique username associated with the account.
      name:
        type: string
        description: The user's name, as it shows up in the UI.
      email:
        type: string
        description: The user's email address.

  AuthToken:
    type: object
    properties:
      token:
        type: string
        description: The authentication token.
      refresh:
        type: string
        description: The refresh token, used to get a new auth token.
      expires:
        type: string
        description: The timestamp for when the token expires.